import Head from "next/head";
import Image from "next/image";

import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Blodyning</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <div>
          <h1>Blodyning</h1>
          <h2>Platform for free courses on web and mobile development</h2>
        </div>
        <div>
          <Image />
        </div>
      </header>

      <main></main>

      <footer></footer>
      <style jsx>{``}</style>
    </>
  );
}
